version: '2'


services:
  db:
    container_name: database
    env_file:
      - db_credentials.env
    image: obsmulti_db
    ports:
       - "127.0.0.1:3306:3306"

  webapp:
    container_name: webapp
    env_file:
      - db_credentials.env
    image: obsmulti:v1.0
    ports:
      - "0.0.0.0:5000:8080"

  etl:
    container_name: etl
    environment:
      - MYSQL_HOST=database
    env_file:
      - db_credentials.env
    image: etl:v1.0

